<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 sp2 (http://www.altova.com)-->
<Manifest CSUVersion="1.0" xsi:noNamespaceSchemaLocation="CSUManifest.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<UpdateID>update26</UpdateID>
	<OwningChannel>AdobeApplicationManager-1.0</OwningChannel>
	<AAMInfo>
		<Channel>
			<DisplayName>Adobe Application Manager</DisplayName>
		</Channel>
	</AAMInfo>
  <DisplayName default="en_US">
    <ar_AE>Adobe® Application Manager® Self Update</ar_AE>
    <bg_BG>Adobe® Application Manager® Self Update</bg_BG>
    <cs_CZ>Adobe® Application Manager® Self Update</cs_CZ>
    <da_DK>Adobe® Application Manager® Self Update</da_DK>
    <de_DE>Adobe® Application Manager® Self Update</de_DE>
    <el_GR>Adobe® Application Manager® Self Update</el_GR>
    <en_US>Adobe® Application Manager® Self Update</en_US>
    <es_ES>Adobe® Application Manager® Self Update</es_ES>
    <et_EE>Adobe® Application Manager® Self Update</et_EE>
    <fi_FI>Adobe® Application Manager® Self Update</fi_FI>
    <fr_FR>Adobe® Application Manager® Self Update</fr_FR>
    <he_IL>Adobe® Application Manager® Self Update</he_IL>
    <hr_HR>Adobe® Application Manager® Self Update</hr_HR>
    <hu_HU>Adobe® Application Manager® Self Update</hu_HU>
    <it_IT>Adobe® Application Manager® Self Update</it_IT>
    <ja_JP>Adobe® Application Manager® Self アップデート</ja_JP>
    <ko_KR>Adobe® Application Manager® Self 업데이트</ko_KR>
    <lt_LT>Adobe® Application Manager® Self Update</lt_LT>
    <lv_LV>Adobe® Application Manager® Self Update</lv_LV>
    <nb_NO>Adobe® Application Manager® Self Update</nb_NO>
    <nl_NL>Adobe® Application Manager® Self Update</nl_NL>
    <pl_PL>Adobe® Application Manager® Self Update</pl_PL>
    <pt_BR>Adobe® Application Manager® Self Update</pt_BR>
    <ro_RO>Adobe® Application Manager® Self Update</ro_RO>
    <ru_RU>Adobe® Application Manager® Self Update</ru_RU>
    <sk_SK>Adobe® Application Manager® Self Update</sk_SK>
    <sl_SI>Adobe® Application Manager® Self Update</sl_SI>
    <sv_SE>Adobe® Application Manager® Self Update</sv_SE>
    <tr_TR>Adobe® Application Manager® Self Update</tr_TR>
    <uk_UA>Adobe® Application Manager® Self Update</uk_UA>
    <zh_CN>Adobe® Application Manager® Self 更新</zh_CN>
    <zh_TW>Adobe® Application Manager® Self 更新</zh_TW>
  </DisplayName>
  <Description default="en_US">
		<en_US>Required to keep Adobe applications up to date, includes Adobe Software Integrity Service</en_US>
		<cs_CZ>Nezbytný nástroj k zajištění aktualizací pro aplikace Adobe. Součástí je služba Adobe Software Integrity Service</cs_CZ>
		<da_DK>Påkrævet for at holde Adobe-programmer opdateret, omfatter Adobe Software Integrity Service</da_DK>
		<de_DE>Erforderlich, um Adobe-Applikationen auf dem neuesten Stand zu halten. Umfasst Adobe Software Integrity Service</de_DE>
		<es_ES>Necesario para mantener las aplicaciones de Adobe actualizadas. Incluye Adobe Software Integrity Service.</es_ES>
		<es_MX>Necesario para mantener las aplicaciones de Adobe actualizadas. Incluye Adobe Software Integrity Service.</es_MX>
		<fi_FI>Tarvitaan Adoben sovellusten pitämiseksi ajan tasalla, sisältää Adobe Software Integrity Servicen</fi_FI>
		<fr_FR>Nécessaire pour garder les applications Adobe à jour, y compris Adobe Software Integrity Service</fr_FR>
		<fr_CA>Nécessaire pour garder les applications Adobe à jour, y compris Adobe Software Integrity Service</fr_CA>
		<it_IT>Richiesto per mantenere le applicazioni Adobe aggiornate. Comprende Adobe Software Integrity Service</it_IT>
		<ja_JP>Adobe Software Integrity Service を含むアドビアプリケーションを最新の状態に保つ必要があります</ja_JP>
		<ko_KR>Adobe 응용 프로그램을 최신 상태로 유지하기 위해 필요하며, Adobe Software Integrity Service를 포함합니다</ko_KR>
		<nb_NO>Nødvendig for å holde Adobe-applikasjoner oppdatert, inkludert Adobe Software Integrity Service</nb_NO>
		<nl_NL>Vereist om Adobe-toepassingen up-to-date te houden. Bevat Adobe Software Integrity Service</nl_NL>
		<pl_PL>Wymagany do aktualizacji aplikacji Adobe. Zawiera usługę Adobe Software Integrity Service</pl_PL>
		<pt_BR>Necessário para manter os aplicativos da Adobe atualizados, inclui o Adobe Software Integrity Service</pt_BR>
		<ru_RU>Необходим для поддержки актуальности приложений Adobe. Включает службу Adobe Software Integrity Service.</ru_RU>
		<sv_SE>Krävs för att hålla Adobe-program uppdaterade, inklusive Adobe Software Integrity Service</sv_SE>
		<tr_TR>Adobe uygulamalarının güncel tutulması için gereklidir, Adobe Software Integrity Service'ı içerir</tr_TR>
		<zh_CN>需要始终将 Adobe 应用程序保持为最新版本，包括 Adobe Software Integrity Service</zh_CN>
		<zh_TW>必須讓 Adobe 應用程式保持最新狀態，包含 Adobe Software Integrity Service</zh_TW>
  </Description>
  <AffectedChannels>
    <ChannelID>AdobeApplicationManager-1.0</ChannelID>
  </AffectedChannels>
<Dependency>
</Dependency>		
	<Notify>0</Notify>
	<WhenApply>2</WhenApply>
	<InstallFiles>
		<File>
			<Name>SelfUpdate.zip</Name>
			<Type>1</Type>
     			<ExecutableName> set-up.exe</ExecutableName>
			<SilentExecutableArgs>--action=update</SilentExecutableArgs>
			<Size>214771</Size>
		</File>
	</InstallFiles>
	<NeedsReboot>false</NeedsReboot>
</Manifest>
